name: Update ORU Schedule

on:
  schedule:
    - cron: "0 1 * * *" 
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: 
           pip install --upgrade pip
           pip install --no-deps ics==0.7 tatsu==4.4.0
           pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/oru_schedule.ics
          git commit -m "Update ICS file" || echo "No changes to commit"
          git push
