name: Update ORU Schedule

on:
  schedule:
    - cron: "0 1 * * *"  
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clean install dependencies
        run: |
          pip uninstall -y ics tatsu || true
          pip install --no-cache-dir --force-reinstall -r requirements.txt

      - name: Verify installed versions
        run: |
          pip show ics | grep Version || true
          pip show tatsu | grep Version || true

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [ -f docs/oru_schedule.ics ]; then
            git add docs/oru_schedule.ics
            git commit -m "Update ICS file" || echo "no changes to commit"
            git push
          else
            echo "no ics file generated, skipping commit"
          fi
